create or replace view DATATABLES_PROD.PATRIMOINE_CLASSE2.V_EMBASEMENT_NAV(
	NO_PARUTION,
	DATE_PARUTION,
	DATE_DEBUT_SEMAINE,
	DATE_FIN_SEMAINE,
	SEG_ABONNE,
	SOUS_SEG_ABONNE,
	FREQ_VISITES_APP,
	FREQ_VISITES_SITE_MOBILE,
	FREQ_VISITES_DESKTOP,
	FREQ_VISITES_GLOBALE,
	FREQ_VISITES_BOUTIQUE_APP,
	FREQ_VISITES_BOUTIQUE_SITE_MOBILE,
	FREQ_VISITES_BOUTIQUE_DESKTOP,
	FREQ_VISITES_BOUTIQUE_GLOBALE,
	FREQ_VISITES_BOUTIQUE_APP_CONVERTIE,
	FREQ_VISITES_BOUTIQUE_SITE_MOBILE_CONVERTIE,
	FREQ_VISITES_BOUTIQUE_DESKTOP_CONVERTIE,
	FREQ_VISITES_BOUTIQUE_CONVERTIE_GLOBALE
) as 

SELECT

-- Embasement + Calendrier
    cal.NO_PARUTION,
    cal.DATE_PARUTION,
    cal.DATE_DEBUT_SEMAINE,
    cal.DATE_FIN_SEMAINE,       
    COALESCE(emb.SEG_ABONNE, 'Hors abonné')                                                                                     AS SEG_ABONNE,
    COALESCE(emb.SOUS_SEG_ABONNE, 'Anonyme')                                                                                    AS SOUS_SEG_ABONNE,
                                        
-- Piano                                                                
    COUNT_IF(rs.SITE IN ('_Mobiles','_Tablettes'))                                                                              AS FREQ_VISITES_APP,
    COUNT_IF(rs.SITE = 'Site mobile')                                                                                           AS FREQ_VISITES_SITE_MOBILE,
    COUNT_IF(rs.SITE = 'Le Point')                                                                                              AS FREQ_VISITES_DESKTOP,
    FREQ_VISITES_APP + FREQ_VISITES_SITE_MOBILE + FREQ_VISITES_DESKTOP                                                          AS FREQ_VISITES_GLOBALE,
    COUNT_IF(evt.SITE_LEVEL2 = '_Abonnement' AND rs.SITE IN ('_Mobiles','_Tablettes'))                                          AS FREQ_VISITES_BOUTIQUE_APP,
    COUNT_IF(evt.SITE_LEVEL2 = '_Abonnement' AND rs.SITE = 'Site mobile')                                                       AS FREQ_VISITES_BOUTIQUE_SITE_MOBILE,
    COUNT_IF(evt.SITE_LEVEL2 = '_Abonnement' AND rs.SITE = 'Le Point')                                                          AS FREQ_VISITES_BOUTIQUE_DESKTOP,
    FREQ_VISITES_BOUTIQUE_APP + FREQ_VISITES_BOUTIQUE_SITE_MOBILE + FREQ_VISITES_BOUTIQUE_DESKTOP                               AS FREQ_VISITES_BOUTIQUE_GLOBALE,
    COUNT_IF(evt.SITE_LEVEL2 = '_Abonnement' AND rs.SITE IN ('_Mobiles','_Tablettes') AND ZEROIFNULL(rc.FLG_GLOBAL) = 1)        AS FREQ_VISITES_BOUTIQUE_APP_CONVERTIE,
    COUNT_IF(evt.SITE_LEVEL2 = '_Abonnement' AND rs.SITE = 'Site mobile' AND ZEROIFNULL(rc.FLG_GLOBAL) = 1)                     AS FREQ_VISITES_BOUTIQUE_SITE_MOBILE_CONVERTIE,
    COUNT_IF(evt.SITE_LEVEL2 = '_Abonnement' AND rs.SITE = 'Le Point' AND ZEROIFNULL(rc.FLG_GLOBAL) = 1)                        AS FREQ_VISITES_BOUTIQUE_DESKTOP_CONVERTIE,
    FREQ_VISITES_BOUTIQUE_APP_CONVERTIE + FREQ_VISITES_BOUTIQUE_SITE_MOBILE_CONVERTIE + FREQ_VISITES_BOUTIQUE_DESKTOP_CONVERTIE AS FREQ_VISITES_BOUTIQUE_CONVERTIE_GLOBALE
    

    
FROM PIANO_SHARE.DATA.EVENTS evt
INNER JOIN DATATABLES_PROD.PATRIMOINE_REFERENCES.REF_SITES rs ON rs.SITE_ID = evt.SITE_ID
LEFT JOIN DATATABLES_PROD.PATRIMOINE_CLASSE2.DT_EMBASEMENT emb ON emb.COMPTE_ID_UTILISATEUR::VARCHAR = evt.USER_ID::VARCHAR AND DATE(evt.VISIT_TIME) BETWEEN emb.DATE_DEBUT_SEMAINE AND emb.DATE_FIN_SEMAINE
LEFT JOIN DATATABLES_PROD.PATRIMOINE_REFERENCES.REF_COMMANDES_PIANO rc ON rc.EVENT_NAME = evt.EVENT_NAME AND rc.PAGE_FULL_NAME = COALESCE(evt.PAGE_FULL_NAME,'')
CROSS JOIN DATATABLES_PROD.PATRIMOINE_CLASSE1.V_CALENDRIER_PARUTIONS cal 


WHERE
    DATE(evt.VISIT_TIME) BETWEEN cal.DATE_DEBUT_SEMAINE AND cal.DATE_FIN_SEMAINE
    AND cal.FLG_HORS_SERIE = 0
--    AND DATE(evt.VISIT_TIME) >= CURRENT_DATE - 10 -- Pour les tests
GROUP BY ALL
;
